// AUTO-GENERATED by ui_codegen from C:\Users\tvolo\dev\ai-dala\zig-gui\src\screens\example.ui — DO NOT EDIT
// Run `zig build codegen` to regenerate.

const m06 = @import("../../docs/specs/06.types.zig");
const NodeDesc  = m06.NodeDesc;
const Attr      = m06.Attr;
const AttrValue = m06.AttrValue;

pub const root_node_c0_a = [_]Attr{
    .{ .name = "text", .value = .{ .literal = "Hello" } },
};
pub const root_node_c0 = NodeDesc{
    .tag = "Text",
    .classes = "",
    .attrs = &root_node_c0_a,
    .children = &.{},
};

pub const root_node_c1_a = [_]Attr{
    .{ .name = "text", .value = .{ .literal = "Click me" } },
};
pub const root_node_c1 = NodeDesc{
    .tag = "Button",
    .classes = "bg-accent px-4 py-2",
    .attrs = &root_node_c1_a,
    .children = &.{},
};

pub const root_node = NodeDesc{
    .tag = "Column",
    .classes = "p-4 gap-4",
    .attrs = &.{},
    .children = &[_]NodeDesc{ root_node_c0, root_node_c1 },
};

