//! BindingSet and TextBinding — static screen data bindings (R23 / M2-04).
//!
//! INV-4.1: Static screens bind via comptime-resolved field offsets — type-checked,
//! zero runtime path resolution. No string lookup or hash lookup occurs at runtime.
//!
//! Binding lifetime:
//!   - Signal must outlive BindingSet (or the last refresh() call).
//!   - Scene must outlive BindingSet.
//!   - BindingSet does NOT own Signal instances — those are owned by the application
//!     state struct, which is owned by the application.
//!   - After scene.reset() (screen navigation), BindingSet must also be reset — element
//!     indices become invalid. Screen navigation is post-v1; reset is not implemented here.

const std = @import("std");
const signal = @import("signal.zig");
const m07 = @import("../07/types.zig");

const Signal = signal.Signal;
const Scene = m07.Scene;

/// A registered connection between one Signal([]const u8) and one element index.
pub const TextBinding = struct {
    element_idx: u32,
    /// Type-erased pointer to a live Signal([]const u8).
    signal_ptr: *anyopaque,
    /// Reads the current string value from the signal. Points to a function
    /// generated by bindText that knows the concrete type — no vtable overhead.
    read_fn: *const fn (*const anyopaque) []const u8,
};

/// Collection of all active data bindings for a static screen.
/// Lives as a field on App (initialized empty in App.init).
pub const BindingSet = struct {
    text: std.ArrayListUnmanaged(TextBinding) = .empty,

    pub fn init() BindingSet {
        return .{};
    }

    pub fn deinit(self: *BindingSet, gpa: std.mem.Allocator) void {
        self.text.deinit(gpa);
    }

    /// Copy every bound signal's current text into the matching Scene element slot.
    /// Called once per dirty frame by App.run() before Scene.measurePass.
    pub fn refresh(self: *const BindingSet, scene: *Scene) void {
        for (self.text.items) |b| {
            const text_val = b.read_fn(b.signal_ptr);
            scene.setText(b.element_idx, text_val);
        }
    }

    /// Bind a Signal([]const u8) field to a text element.
    ///
    /// Comptime: StateType is the application state struct type; field_name is the
    /// field name as a string literal. The compiler verifies at compile time that
    /// StateType.field_name is exactly Signal([]const u8).
    ///
    /// Runtime: subscribes element_idx to the signal (so signal.set() marks it dirty)
    /// and appends a TextBinding entry for refresh().
    pub fn bindText(
        self: *BindingSet,
        comptime StateType: type,
        comptime field_name: []const u8,
        state: *StateType,
        element_idx: u32,
        gpa: std.mem.Allocator,
    ) !void {
        // COMPILE-TIME check: the named field must be exactly Signal([]const u8).
        comptime {
            const FieldType = @TypeOf(@field(@as(StateType, undefined), field_name));
            if (FieldType != Signal([]const u8)) {
                @compileError("bindText: field '" ++ field_name ++
                    "' must be Signal([]const u8), got " ++ @typeName(FieldType));
            }
        }

        // RUNTIME: resolve field pointer via @field — comptime-resolved offset, no
        // string lookup at runtime (INV-4.1).
        const sig: *Signal([]const u8) = &@field(state.*, field_name);

        // Subscribe the element to the signal — signal.set() will dirty element_idx.
        try sig.subscribe(element_idx);

        // Generate a typed read function at comptime for zero-overhead read in refresh().
        const ReadFns = struct {
            fn read(ptr: *const anyopaque) []const u8 {
                return @as(*const Signal([]const u8), @ptrCast(@alignCast(ptr))).get();
            }
        };

        try self.text.append(gpa, .{
            .element_idx = element_idx,
            .signal_ptr = sig,
            .read_fn = &ReadFns.read,
        });
    }
};
