//! string_table_codegen — Build-time string table codegen tool (M15-03 / RE2).
//!
//! Reads a flat key=value string file (strings.en.txt) and emits a Zig source file
//! containing a `strings` struct with one `pub const` per key and a comptime `t()`
//! lookup function.
//!
//! Usage: string_table_codegen <input.txt> <output.zig>
//! Exit code 0: output file written, valid Zig source.
//! Exit code 1: parse error, duplicate key, or invalid key — diagnostic to stderr.
//!
//! Input format:
//!   # Lines starting with # are comments (ignored).
//!   Empty lines are ignored.
//!   key=value  — one entry per line.
//!   Keys must match [a-zA-Z0-9._-]+.
//!   Values are UTF-8 and may contain {placeholder} markers.

const std = @import("std");

pub fn main(init: std.process.Init) !void {
    const allocator = init.gpa;
    const io = init.io;
    const cwd = std.Io.Dir.cwd();

    const arg_slice = try init.minimal.args.toSlice(init.arena.allocator());

    if (arg_slice.len < 3) {
        std.debug.print("usage: string_table_codegen <input.txt> <output.zig>\n", .{});
        std.process.exit(1);
    }

    const input_path = arg_slice[1];
    const output_path = arg_slice[2];

    // Use an arena for all allocations so they are freed on exit.
    var arena = std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    const aalloc = arena.allocator();

    // Read the input file.
    const source = std.Io.Dir.readFileAlloc(cwd, io, input_path, aalloc, .unlimited) catch |err| {
        std.debug.print("error reading '{s}': {}\n", .{ input_path, err });
        std.process.exit(1);
    };

    // Parse key=value pairs.
    var entries = std.ArrayList(Entry).empty;
    defer entries.deinit(aalloc);

    var line_iter = std.mem.tokenizeScalar(u8, source, '\n');
    while (line_iter.next()) |line| {
        const trimmed = std.mem.trim(u8, line, " \t\r");
        if (trimmed.len == 0) continue;
        if (trimmed[0] == '#') continue;

        // Split on first '='.
        const eq_pos = std.mem.indexOfScalar(u8, trimmed, '=') orelse {
            std.debug.print("{s}: error: line missing '=' separator: '{s}'\n", .{ input_path, trimmed });
            std.process.exit(1);
        };
        if (eq_pos == 0) {
            std.debug.print("{s}: error: empty key on line: '{s}'\n", .{ input_path, trimmed });
            std.process.exit(1);
        }

        const key = trimmed[0..eq_pos];
        const value = trimmed[eq_pos + 1 ..];

        // Validate key.
        if (!isValidKey(key)) {
            std.debug.print("{s}: error: invalid key '{s}' — keys must match [a-zA-Z0-9._-]+\n", .{ input_path, key });
            std.process.exit(1);
        }

        // Check for duplicate.
        for (entries.items) |entry| {
            if (std.mem.eql(u8, entry.key, key)) {
                std.debug.print("{s}: error: duplicate key '{s}'\n", .{ input_path, key });
                std.process.exit(1);
            }
        }

        try entries.append(aalloc, .{
            .key = try aalloc.dupe(u8, key),
            .value = try aalloc.dupe(u8, value),
        });
    }

    if (entries.items.len == 0) {
        std.debug.print("{s}: error: no entries found\n", .{ input_path });
        std.process.exit(1);
    }

    // Generate output.
    var out_buf = std.Io.Writer.Allocating.init(aalloc);
    defer out_buf.deinit();

    try emitStringsFile(&out_buf.writer, input_path, entries.items);

    // Write output file.
    const out_bytes = try out_buf.toOwnedSlice();

    const out_file = std.Io.Dir.createFile(cwd, io, output_path, .{}) catch |err| {
        std.debug.print("error creating '{s}': {}\n", .{ output_path, err });
        std.process.exit(1);
    };
    defer out_file.close(io);
    try std.Io.File.writeStreamingAll(out_file, io, out_bytes);
}

const Entry = struct {
    key: []const u8,
    value: []const u8,
};

/// Emit the entire generated Zig source file.
fn emitStringsFile(writer: anytype, input_path: []const u8, entries: []const Entry) !void {
    try writer.print(
        \\// Generated by string_table_codegen from {s}. DO NOT EDIT.
        \\
        \\const std = @import("std");
        \\
        \\pub const strings = struct {{
        \\
        ,
        .{input_path},
    );

    // Emit one pub const per key.
    for (entries) |entry| {
        try writer.writeAll("    pub const ");
        try writeDeclName(writer, entry.key);
        try writer.writeAll(": []const u8 = ");
        try writeEscapedString(writer, entry.value);
        try writer.writeAll(";\n");
    }

    // Emit the t() lookup function.
    try writer.writeAll(
        \\    pub fn t(comptime key: []const u8) []const u8 {
        \\
    );

    for (entries) |entry| {
        try writer.writeAll("        if (comptime std.mem.eql(u8, key, ");
        try writeEscapedString(writer, entry.key);
        try writer.writeAll(")) return ");
        try writeDeclName(writer, entry.key);
        try writer.writeAll(";\n");
    }

    try writer.writeAll(
        \\        @compileError("unknown string key: " ++ key);
        \\    }
        \\};
        \\
    );
}

/// Validate that key matches [a-zA-Z0-9._-]+
fn isValidKey(key: []const u8) bool {
    if (key.len == 0) return false;
    for (key) |c| {
        const valid = switch (c) {
            'a'...'z', 'A'...'Z', '0'...'9', '.', '_', '-' => true,
            else => false,
        };
        if (!valid) return false;
    }
    return true;
}

/// Write a Zig declaration name for the given key.
/// For keys containing dots, wraps in @"..." syntax.
fn writeDeclName(writer: anytype, key: []const u8) !void {
    if (std.mem.indexOfScalar(u8, key, '.') != null) {
        try writer.writeAll("@\"");
        try writer.writeAll(key);
        try writer.writeByte('"');
    } else {
        try writer.writeAll(key);
    }
}

fn writeEscapedString(writer: anytype, s: []const u8) !void {
    try writer.writeByte('"');
    for (s) |c| {
        switch (c) {
            '"'  => try writer.writeAll("\\\""),
            '\\'  => try writer.writeAll("\\\\"),
            '\n' => try writer.writeAll("\\n"),
            '\r' => try writer.writeAll("\\r"),
            '\t' => try writer.writeAll("\\t"),
            0x00...0x08, 0x0B...0x0C, 0x0E...0x1F, 0x7F...0xFF => try writer.print("\\x{X:0>2}", .{c}),
            else => try writer.writeByte(c),
        }
    }
    try writer.writeByte('"');
}
