//! ui_codegen — Build-time codegen tool for .ui markup files (R55 / M5-06).
//!
//! Reads one .ui file and emits a .zig file containing baked NodeDesc struct literals.
//! The production binary imports the generated file and never calls the parser at runtime (INV-4.4).
//!
//! Usage: ui_codegen <input.ui> <output.zig>
//! Exit code 0: output file written, valid Zig source.
//! Exit code 1: diagnostic to stderr, no output file written.

const std = @import("std");
const m06 = @import("m06");

const NodeDesc = m06.NodeDesc;
const Attr = m06.Attr;
const AttrValue = m06.AttrValue;
const parseWithDiag = m06.parseWithDiag;
const ParseDiagnostic = m06.ParseDiagnostic;

pub fn main(init: std.process.Init) !void {
    const allocator = init.gpa;
    const io = init.io;
    const cwd = std.Io.Dir.cwd();

    const arg_slice = try init.minimal.args.toSlice(init.arena.allocator());

    if (arg_slice.len < 3) {
        std.debug.print("usage: ui_codegen <input.ui> <output.zig>\n", .{});
        std.process.exit(1);
    }

    const input_path  = arg_slice[1];
    const output_path = arg_slice[2];

    const source = std.Io.Dir.readFileAlloc(cwd, io, input_path, allocator, .unlimited) catch |err| {
        std.debug.print("error reading '{s}': {}\n", .{ input_path, err });
        std.process.exit(1);
    };
    defer allocator.free(source);

    var arena = std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();

    var diag: ParseDiagnostic = undefined;
    const root = parseWithDiag(arena.allocator(), source, &diag) catch |err| {
        if (err != error.OutOfMemory) {
            std.debug.print("{s}:{}:{}: error: {s}\n",
                .{ input_path, diag.loc.line, diag.loc.column, diag.message });
        } else {
            std.debug.print("out of memory\n", .{});
        }
        std.process.exit(1);
    };

    var out_buf = std.Io.Writer.Allocating.init(allocator);
    defer out_buf.deinit();

    try emitHeader(&out_buf.writer, input_path);
    try emitNodeDecl(&out_buf.writer, allocator, root, "root_node", 0);

    const out_bytes = try out_buf.toOwnedSlice();
    defer allocator.free(out_bytes);

    const out_file = std.Io.Dir.createFile(cwd, io, output_path, .{}) catch |err| {
        std.debug.print("error creating '{s}': {}\n", .{ output_path, err });
        std.process.exit(1);
    };
    defer out_file.close(io);
    try std.Io.File.writeStreamingAll(out_file, io, out_bytes);
}

fn emitHeader(writer: anytype, input_path: []const u8) !void {
    try writer.print(
        \\// AUTO-GENERATED by ui_codegen from {s} — DO NOT EDIT
        \\// Run `zig build codegen` to regenerate.
        \\
        \\const m06 = @import("../../docs/specs/06.types.zig");
        \\const NodeDesc  = m06.NodeDesc;
        \\const Attr      = m06.Attr;
        \\const AttrValue = m06.AttrValue;
        \\
        \\
        ,
        .{input_path},
    );
}

fn emitNodeDecl(
    writer: anytype,
    allocator: std.mem.Allocator,
    node: NodeDesc,
    decl_name: []const u8,
    depth: u32,
) !void {
    _ = depth;

    // Emit children first (bottom-up), collect their declaration names.
    var child_names = std.ArrayList([]const u8).empty;
    defer {
        for (child_names.items) |n| allocator.free(n);
        child_names.deinit(allocator);
    }

    for (node.children, 0..) |child, i| {
        var name_buf: [256]u8 = undefined;
        const child_name = std.fmt.bufPrint(&name_buf, "{s}_c{d}", .{ decl_name, i }) catch "child";
        const owned_name = try allocator.dupe(u8, child_name);
        try child_names.append(allocator, owned_name);
        try emitNodeDecl(writer, allocator, child, owned_name, 0);
    }

    // Emit attrs array (if any).
    const attrs_name = blk: {
        if (node.attrs.len == 0) {
            break :blk @as([]const u8, ".{}");
        }
        var name_buf: [256]u8 = undefined;
        const aname = std.fmt.bufPrint(&name_buf, "{s}_a", .{decl_name}) catch "attrs";
        const owned_aname = try allocator.dupe(u8, aname);
        defer allocator.free(owned_aname);

        try writer.print("pub const {s} = [_]Attr{{\n", .{owned_aname});
        for (node.attrs) |attr| {
            try writer.writeAll("    .{ .name = ");
            try writeEscapedString(writer, attr.name);
            try writer.writeAll(", .value = ");
            switch (attr.value) {
                .literal => |s| {
                    try writer.writeAll(".{ .literal = ");
                    try writeEscapedString(writer, s);
                    try writer.writeAll(" }");
                },
                .bind => |s| {
                    try writer.writeAll(".{ .bind = ");
                    try writeEscapedString(writer, s);
                    try writer.writeAll(" }");
                },
            }
            try writer.writeAll(" },\n");
        }
        try writer.writeAll("};\n");

        var result_buf: [256]u8 = undefined;
        const ref = try std.fmt.bufPrint(&result_buf, "&{s}", .{owned_aname});
        break :blk try allocator.dupe(u8, ref);
    };
    // Free the allocated attrs_name slice if one was produced.
    defer if (node.attrs.len > 0) allocator.free(attrs_name);

    // Build children reference string.
    var children_ref_buf = std.ArrayList(u8).empty;
    defer children_ref_buf.deinit(allocator);
    for (child_names.items, 0..) |cname, i| {
        if (i > 0) try children_ref_buf.appendSlice(allocator, ", ");
        try children_ref_buf.appendSlice(allocator, cname);
    }

    // Emit node declaration.
    try writer.print("pub const {s} = NodeDesc{{\n", .{decl_name});
    try writer.writeAll("    .tag = ");
    try writeEscapedString(writer, node.tag);
    try writer.writeAll(",\n");
    try writer.writeAll("    .classes = ");
    try writeEscapedString(writer, node.classes);
    try writer.writeAll(",\n");
    if (node.attrs.len == 0) {
        try writer.writeAll("    .attrs = &.{},\n");
    } else {
        try writer.print("    .attrs = {s},\n", .{attrs_name});
    }
    if (child_names.items.len == 0) {
        try writer.writeAll("    .children = &.{},\n");
    } else {
        try writer.print("    .children = &[_]NodeDesc{{ {s} }},\n", .{children_ref_buf.items});
    }
    try writer.writeAll("};\n\n");
}

fn writeEscapedString(writer: anytype, s: []const u8) !void {
    try writer.writeByte('"');
    for (s) |c| {
        switch (c) {
            '"'  => try writer.writeAll("\\\""),
            '\\'  => try writer.writeAll("\\\\"),
            '\n' => try writer.writeAll("\\n"),
            '\r' => try writer.writeAll("\\r"),
            '\t' => try writer.writeAll("\\t"),
            0x00...0x08, 0x0B...0x0C, 0x0E...0x1F, 0x7F...0xFF => try writer.print("\\x{X:0>2}", .{c}),
            else => try writer.writeByte(c),
        }
    }
    try writer.writeByte('"');
}
